### PR TITLE
revised for upper body

### PR DESCRIPTION
**Pull request by harmooni**
Hi Will,
this is the revised version for the upper body, I have an extra branch for the new cutout.

### CODE REVIEW

**Comment by harmooni** [comment]
How should we proceed with the cutout branch?

**Comment by wspr** [comment]
I really have to sleep right now, but is the cutout branch two things? (a) both a different integral for the calculations, AND (b) the improvements to the plotting functions? If so, we could either 

1.  Merge across just the plots, even if they're not 100% representative of Hatze's original integral (since they ARE representative of his intent).
2.  Create a cutout branch in my repository as well and just merge the whole thing across, continuing to develop in parallel for the time being.

What do you think sounds best?

**Comment by wspr** [comment]
(Also happy to do whatever's easiest for now!)

**Comment by harmooni** [comment]
No, all of my changes are also in the master branch except for the different integral for the cutout in the shoulder segment which is in the cutout branch. 
So you can merge with my master branch. And add the integrals (which is not much) manually with a switch you wanted to make.

**Pull request merged**
